package com.minglyu.mybatisgeneratordemo.mappers.auto;

import com.minglyu.mybatisgeneratordemo.entities.Coffee;
import com.minglyu.mybatisgeneratordemo.entities.CoffeeCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CoffeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffees
     *
     * @mbg.generated
     */
    long countByExample(CoffeeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffees
     *
     * @mbg.generated
     */
    int deleteByExample(CoffeeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffees
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffees
     *
     * @mbg.generated
     */
    int insert(Coffee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffees
     *
     * @mbg.generated
     */
    int insertSelective(Coffee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffees
     *
     * @mbg.generated
     */
    List<Coffee> selectByExampleWithRowbounds(CoffeeCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffees
     *
     * @mbg.generated
     */
    List<Coffee> selectByExample(CoffeeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffees
     *
     * @mbg.generated
     */
    Coffee selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffees
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Coffee record, @Param("example") CoffeeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffees
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Coffee record, @Param("example") CoffeeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffees
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Coffee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffees
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Coffee record);
}